version: '3.7'

services:

  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=gamificator_db
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=secret
    ports:
      - 3306:3306
    volumes:
      - ./docker/database/:/docker-entrypoint-initdb.d/
      - gamificator_vol:/var/lib/mysql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    networks:
      - backend


# for debug
  adminer:
    image: adminer
    container_name: admirer
    restart: always
    ports:
      - 8888:8080
    networks:
      - backend
  
  
  app:
    image: ghcr.io/digitalpatate/gamificator:latest
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/gamificator_db
      - SPRING_DATASOURCE_USERNAME=springuser
      - SPRING_DATASOURCE_PASSWORD=secret
    depends_on:
      - db
    ports:
     - 8080:8080
    networks:
      - backend
      
networks:
  backend:
    external: false


volumes:
  gamificator_vol:
    external: false